name: build and deploy
on:
  push:
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: build
        run: |
          cd src
          yarn install
          yarn build
          cp *.db dist/
      - name: deploy
        run: |
          cd src
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -u "github-actions-bot <support+action@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
